# Copyright (c) 2025 Qualcomm Innovation Center, Inc. All rights reserved.
# SPDX-License-Identifier: BSD-3-Clause-Clear
#
# eMMC 16GB partition layout for UnoQ (Arduino variant).
# Adds a userdata partition on top of the base layout.

%include ../emmc-16GB/partitions.conf
--partition --name=userdata --size=2145728KB --type-guid=B921B045-1DF0-41C3-AF44-4C6F280D3FAE --filename=userdata.img
