# Copyright (c) 2026 Qualcomm Innovation Center, Inc. All rights reserved.
# SPDX-License-Identifier: BSD-3-Clause-Clear
#
# Combined NVMe + SPINOR partition layout for IQ-X7181 EVK.
# NHLOS firmware on SPINOR, HLOS (Linux) on NVMe.

%include ../spinor/partitions.conf
%include ../nvme/partitions.conf
